<?php

/**
 * GENERATED by command:
 * php artisan make:controller HomeController
 */

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    // Actions, which will be next called in route file
    public function home(){
        return view('home.index');
    }

    public function contact(){
        return view('home.contact');
    }
}
